# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_url', models.URLField(unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
