# Generated by Django 4.2.4 on 2023-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211106_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunny',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
