# Generated by Django 4.2.4 on 2023-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_bunny_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunny',
            old_name='comment_url',
            new_name='main_url',
        ),
    ]
