# Generated by Django 4.2.4 on 2023-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_comment_url_bunny_main_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunny',
            name='permission_error',
            field=models.BooleanField(default=False),
        ),
    ]
